[package]
name = "url-shortener"
version = "0.1.0"
authors = ["goldsborough <peter@goldsborough.me>"]

[dependencies]
hyper = "0.11.13"
futures = "0.1.17"
url = "1.6.0"
futures-cpupool = "0.1.8"
pretty_env_logger = "0.1.1"
log = "0.4.1"
postgres = "0.15.1"
diesel = "1.1.0"
